# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{atlas_middleware}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin Casey"]
  s.date = %q{2009-09-23}
  s.description = %q{Middleware components for Atlas Projects}
  s.email = %q{casey.colin@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "lib/arc_server_soap.rb",
     "lib/atlas_middleware.rb",
     "lib/cgns_search.rb",
     "lib/esri/soap/map_server/classes.rb",
     "lib/esri/soap/map_server/client.rb",
     "lib/esri/soap/map_server/map_server.rb",
     "lib/esri/soap/map_server/mapping_registry.rb",
     "lib/map_server_legend_info.rb",
     "lib/pdf_template.rb",
     "lib/postal_code_lookup.rb",
     "lib/print_map/job.rb",
     "lib/print_map/legend_images_collector.rb",
     "lib/print_map/map_exporter.rb",
     "lib/print_map/pdf_generator.rb",
     "lib/print_map/worker.rb",
     "lib/print_map_service.rb",
     "lib/rest_proxy.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Middleware components for Atlas Projects}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<soap4r>, [">= 0"])
      s.add_runtime_dependency(%q<arcserver.rb>, [">= 0"])
    else
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<soap4r>, [">= 0"])
      s.add_dependency(%q<arcserver.rb>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<soap4r>, [">= 0"])
    s.add_dependency(%q<arcserver.rb>, [">= 0"])
  end
end
